verify token is functional when fetching secrets from another github environment

diff --git a/.github/workflows/get-secret-from-environment.yml b/.github/workflows/get-secret-from-environment.yml
--- a/.github/workflows/get-secret-from-environment.yml
+++ b/.github/workflows/get-secret-from-environment.yml
@@ -43,6 +43,17 @@ jobs:
             exit 1
           fi
 
+      - name: Verify GitHub token validity
+        id: verify-token
+        run: |
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.gh_token }}" \
+                            "https://api.github.com/user")
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "Invalid or expired GitHub token."
+            exit 1
+          fi
+          echo "GitHub token is valid."
+
       - name: Check if environment exists
         id: check-env
         run: |
